context:
  name: cuda-pathfinder
  version: "1.1.0"
  # no-arch packages can't use selectors, so we avoid using the "match(python, "<3.9")" selector this way
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/cuda-python/releases/download/${{ name }}-v${{ version }}/cuda-python-${{ name }}-v${{ version }}.tar.gz
  sha256: 7784a99f24efff5a3c097b9b8d7ccf71dc710a7c9ee9f78ac0084cbb38668b57

build:
  noarch: python
  script: cd cuda_pathfinder && python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - cuda-version >=11.0,<14

tests:
  - python:
      imports:
      - cuda.pathfinder
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  # TODO: update the url once the docs is up
  homepage: https://nvidia.github.io/cuda-python/latest/
  summary: 'cuda.pathfinder: Utilities for locating CUDA components in a Python virtual environment'
  description: |
    Public API for loading NVIDIA Dynamic Libraries
  license: Apache-2.0
  license_file: cuda_pathfinder/LICENSE
  # TODO: update the url once the docs is up
  documentation: https://nvidia.github.io/cuda-python/latest/
  repository: https://github.com/NVIDIA/cuda-python/tree/main/cuda_pathfinder

extra:
  recipe-maintainers:
    - rwgk
    - leofang
    - kkraus14
    - oleksandr-pavlyk
    - bdice
